const AMAZON_ASSOCIATE_TAG = (import.meta.env.VITE_AMAZON_ASSOCIATE_TAG || "deluluromance-21").trim();

export function amazonProductUrl(asin) {
  const url = new URL(`https://www.amazon.in/dp/${asin}`);
  if (AMAZON_ASSOCIATE_TAG) url.searchParams.set("tag", AMAZON_ASSOCIATE_TAG);
  return url.toString();
}

export const amazonAffiliateConfigured = Boolean(AMAZON_ASSOCIATE_TAG);

export const AMAZON_COLLECTIONS = [
  {
    id: "tennis-balls",
    label: "Tennis ball cricket",
    eyebrow: "Street · society · training",
    title: "Tennis-ball match kits",
    description: "Lighter, forgiving options for gully cricket, society matches, indoor practice and everyday throwdowns.",
    accent: "cyan",
    products: [
      { asin: "B06XPCT8V8", price: "₹403", title: "Cosco Rubber Light Cricket Tennis Ball (Pack of 6)", image: "https://m.media-amazon.com/images/I/71QtQyiWYJL._AC_UL320_.jpg", fit: "A familiar six-ball pack for casual matches and club practice." },
      { asin: "B0H7HPT7MY", price: "₹299", title: "Tennis Ball for Cricket Pack of 12", image: "https://m.media-amazon.com/images/I/81bn-9twrdL._AC_UL320_.jpg", fit: "A bigger practice pack for nets, lawns and tournament warm-ups." },
      { asin: "B0DBDHRTKF", price: "₹189", title: "Nivia Heavy Weight Tennis Cricket Ball, Pack of 3", image: "https://m.media-amazon.com/images/I/7191NrZIH9L._AC_UL320_.jpg", fit: "A heavier training feel for players who want more carry off the bat." },
      { asin: "B0DSJLJ6G7", price: "₹299", title: "SLOVIC Practice Tennis Cricket Balls, Pack of 6", image: "https://m.media-amazon.com/images/I/81dh9JNGiHL._AC_UL320_.jpg", fit: "High-bounce rubber balls for street matches and repeat drills." },
      { asin: "B08NXZQN22", price: "₹263", title: "AMiFIT Light Weight Tennis Balls, Pack of 12", image: "https://m.media-amazon.com/images/I/61izfb9T7ZL._AC_UL320_.jpg", fit: "A softer, lighter pick for casual play and younger players." },
      { asin: "B0FQJXNCWH", price: "₹349", title: "Boldfit Lightweight Rubber Tennis Balls, Pack of 6", image: "https://m.media-amazon.com/images/I/51GtP5XjzML._AC_UL320_.jpg", fit: "Court and turf friendly balls for organised practice sessions." },
    ],
  },
  {
    id: "leather-balls",
    label: "Leather-ball cricket",
    search: "leather cricket ball",
    eyebrow: "Club · academy · match play",
    title: "Leather-ball match kits",
    description: "Hand-stitched and club-style options for nets, hard-ball practice, day/night games and match preparation.",
    accent: "gold",
    products: [
      { asin: "B0C6HSCXDR", price: "₹258", title: "Club Leather Cricket Ball, Two-Piece Red/White", image: "https://m.media-amazon.com/images/I/51WJaMMpZwL._AC_UL320_.jpg", fit: "A two-piece club-style ball for match practice and regular sessions." },
      { asin: "B09XJG4YG5", price: "₹159", title: "AK SPORTS Red and White Leather Ball Combo", image: "https://m.media-amazon.com/images/I/51zF50Ss1lL._AC_UL320_.jpg", fit: "A two-ball combo for switching between red and white-ball drills." },
      { asin: "B0G346BXZD", price: "₹183", title: "Hand-Stitched Leather Cricket Ball for Club and Academy Use", image: "https://m.media-amazon.com/images/I/41li1hELD1L._AC_UL320_.jpg", fit: "A water-resistant training option for nets and academy work." },
      { asin: "B09CV7PW14", price: "₹482", title: "SG Shield 20 Red Leather Cricket Ball", image: "https://m.media-amazon.com/images/I/71K9p0st-ZL._AC_UL320_.jpg", fit: "A recognised club-ball option for structured hard-ball practice." },
      { asin: "B0G3P92VFK", price: "₹529", title: "SG Super 50 White Cricket Ball", image: "https://m.media-amazon.com/images/I/51f0-pK7PwL._AC_UL320_.jpg", fit: "A white-ball option for limited-overs and day/night sessions." },
      { asin: "B0GM34HF3X", price: "₹149", title: "PRO T-20 Hand-Stitched Leather Cricket Ball", image: "https://m.media-amazon.com/images/I/41TMpZEGZlL._AC_UL320_.jpg", fit: "A T20-oriented option for swing, seam and match-style drills." },
    ],
  },
  {
    id: "cricket-bats",
    label: "Cricket bats",
    search: "cricket bat",
    eyebrow: "Tennis-ball · willow · match day",
    title: "Bats for every format",
    description: "Plastic, poplar and willow options for backyard games, tennis-ball sessions and leather-ball match preparation.",
    accent: "cyan",
    products: [
      { asin: "B0H36DV4DY", price: "₹279", title: "AXON Full Size Plastic Tennis Cricket Bat (34 Inch)", image: "https://m.media-amazon.com/images/I/513Hq57QwbL._AC_UL320_.jpg", fit: "A lightweight hard-plastic option for tennis-ball cricket and casual matches." },
      { asin: "B0HG78T7GF", price: "₹399", title: "Plastic Cricket Bat Full Size", image: "https://m.media-amazon.com/images/I/51lgP9OV4eL._AC_UL320_.jpg", fit: "A simple full-size pick for gully cricket, practice and family games." },
      { asin: "B0HFJZGKCD", price: "₹5,599", title: "StrikeX Limited Edition Kashmir Willow Cricket Bat", image: "https://m.media-amazon.com/images/I/515BhjVmf8L._AC_UL320_.jpg", fit: "A willow profile for players moving from casual play into structured nets." },
      { asin: "B0HKDCNKZL", price: "₹298", title: "PMG Plastic Cricket Bat with Stumps and Ball", image: "https://m.media-amazon.com/images/I/51VxnoPy0wL._AC_UL320_.jpg", fit: "A ready-to-play starter set for younger players and home cricket." },
      { asin: "B0HFK4M1ZV", price: "₹5,499", title: "Strike X Maximum Premium Willow Cricket Bat", image: "https://m.media-amazon.com/images/I/61qzhF1xLKL._AC_UL320_.jpg", fit: "A fuller willow option for organised practice and match-day preparation." },
      { asin: "B09WVXMG96", price: "₹376", title: "Jaspo SLOG Full Size Plastic Tennis Cricket Bat", image: "https://m.media-amazon.com/images/I/71XGeHFYHML._AC_UL320_.jpg", fit: "A durable plastic bat for society cricket, turf and repeat throwdowns." },
    ],
  },
  {
    id: "batting-gloves",
    label: "Batting gloves",
    search: "cricket batting gloves",
    eyebrow: "Grip · protection · control",
    title: "Batting gloves",
    description: "Grip-focused batting gloves and protective options for nets, society matches and match-day confidence.",
    accent: "gold",
    products: [
      { asin: "B0FY375XYW", price: "₹1,942.05", title: "SHREY Chroma Professional Batting Cricket Gloves", image: "https://m.media-amazon.com/images/I/71PRjL6JoqL._AC_UL320_.jpg", fit: "A boys-size batting glove listing for players who want a snug, protected grip." },
      { asin: "B0BDMRZMT6", price: "₹1,199", title: "Whitedot Dot 2.1 Cricket Batting Gloves", image: "https://m.media-amazon.com/images/I/71o2H0RcewL._AC_UL320_.jpg", fit: "A youth and medium-size option for aspiring batters and training sessions." },
      { asin: "B0BRVF6WGN", price: "₹1,450", title: "THRAX Leather St 1800 Cricket Batting Gloves", image: "https://m.media-amazon.com/images/I/611xibNT9UL._AC_UL320_.jpg", fit: "A standard-size glove listing for organised club cricket and nets." },
      { asin: "B0B2NZMWBD", price: "₹1,050", title: "THRAX Leather Aello X 1 Cricket Batting Gloves", image: "https://m.media-amazon.com/images/I/615MbEyFzyL._AC_UL320_.jpg", fit: "A right-hand batting option with a classic white-and-blue match look." },
      { asin: "B0B2NZ8M5J", price: "₹999", title: "THRAX Leather Aello X 2 Cricket Batting Gloves", image: "https://m.media-amazon.com/images/I/61EKpFjGORL._AC_UL320_.jpg", fit: "A red-and-white right-hand option for players building a match kit." },
      { asin: "B0BDMPLCGC", price: "₹1,199", title: "WHITEDOT Sports Leather Dot 2.1 Batting Gloves", image: "https://m.media-amazon.com/images/I/61tdh7buNAL._AC_UL320_.jpg", fit: "An adult large right-hand listing for regular batting practice and games." },
    ],
  },
  {
    id: "batting-pads",
    label: "Batting pads",
    search: "cricket batting pads",
    eyebrow: "Leg guard · match protection",
    title: "Batting pads",
    description: "Leg protection listings for batting at nets, club games and tournament play. Check handedness and sizing before buying.",
    accent: "cyan",
    products: [
      { asin: "B0FYQ3RN4J", price: "₹3,580.40", title: "Shrey Meta VR Full Size Cricket Batting Pads", image: "https://m.media-amazon.com/images/I/61N2IN1X0yL._AC_UL320_.jpg", fit: "A full-size left-hand legguard listing for match preparation and hard-ball nets." },
      { asin: "B0FY3469SZ", price: "₹3,049", title: "Shrey Chroma Full Size Cricket Batting Pads", image: "https://m.media-amazon.com/images/I/71y6h3sVM4L._AC_UL320_.jpg", fit: "A full-size right-hand option with a clean match-day colourway." },
      { asin: "B0GPXBC8D1", price: "₹4,799", title: "Shrey Legacy Full Size Cricket Batting Pads", image: "https://m.media-amazon.com/images/I/61vOdHqhpJL._AC_UL320_.jpg", fit: "A full-size left-hand leg guard for players building a complete kit." },
      { asin: "B09ND6QB4W", price: "₹1,711", title: "Whitedot Dot 2.1 Black Cricket Batting Pad", image: "https://m.media-amazon.com/images/I/71dh0uaaUTL._AC_UL320_.jpg", fit: "A black adult-size listing for training and regular society matches." },
      { asin: "B08T6CT6NL", price: "₹2,199", title: "Whitedot Dot 2.1 PU Cricket Batting Pads", image: "https://m.media-amazon.com/images/I/715FDtd9U9L._AC_UL320_.jpg", fit: "A youth and medium left-hand pair for training sessions and matches." },
      { asin: "B0HCQXQH9M", price: "₹709", title: "Boy Cricket Batting Legguard Pads", image: "https://m.media-amazon.com/images/I/51xNN9g8a-L._AC_UL320_.jpg", fit: "A junior legguard listing for younger batters learning with confidence." },
    ],
  },
  {
    id: "cricket-helmets",
    label: "Cricket helmets",
    search: "cricket helmet",
    eyebrow: "Head protection · fit first",
    title: "Batting helmets",
    description: "Adjustable grill helmet listings for batters and young players. Confirm size, fit, certification and current safety information on Amazon.",
    accent: "gold",
    products: [
      { asin: "B0DPCJJQ39", price: "₹1,212.75", title: "Shrey Prime Steel Adjustable Grill Cricket Helmet", image: "https://m.media-amazon.com/images/I/81xgT2xFx+L._AC_UL320_.jpg", fit: "A small-size royal-blue steel-grill listing with adjustable fit features." },
      { asin: "B0FDQPZQ5K", price: "₹1,727.21", title: "Shrey Premium 3.0 Steel Adjustable Grill Helmet", image: "https://m.media-amazon.com/images/I/81Gv0rw8kyL._AC_UL320_.jpg", fit: "A small-size green helmet listing for players checking off match protection." },
      { asin: "B0D9JM3GCH", price: "₹1,359", title: "Shrey Star Junior 2.0 Steel Batting Helmet", image: "https://m.media-amazon.com/images/I/81XKPOV8geL._AC_UL320_.jpg", fit: "A junior adjustable-grill listing for developing players." },
      { asin: "B0D9JMVF32", price: "₹1,689", title: "Shrey Match 3.0 Steel Adjustable Grill Helmet", image: "https://m.media-amazon.com/images/I/81Cnlrj13gL._AC_UL320_.jpg", fit: "A large-size sky-blue option for adult match preparation." },
      { asin: "B07YPQ4TY1", price: "₹3,279", title: "Shrey Classic Steel Fixed Visor Cricket Helmet", image: "https://m.media-amazon.com/images/I/81yJ7fVDoXL._AC_UL320_.jpg", fit: "A classic fixed-visor listing for players comparing traditional helmet profiles." },
      { asin: "B0FJG33FKW", price: "₹389", title: "Gmrfvr Adjustable Steel Grill Cricket Helmet", image: "https://m.media-amazon.com/images/I/510iJ-it61L._AC_UL320_.jpg", fit: "A navy adjustable-grill option across adult and junior sizing." },
    ],
  },
  {
    id: "kit-bags",
    label: "Kit bags",
    search: "cricket kit bag",
    eyebrow: "Carry · organise · travel",
    title: "Kit bags and storage",
    description: "Roomy cricket bags for bats, pads, gloves, shoes and match-day accessories, with multiple carry styles to compare.",
    accent: "cyan",
    products: [
      { asin: "B0FWRHJKFR", price: "₹1,049", title: "Boldfit Full Size Cricket Kit Bag with Bat Compartment", image: "https://m.media-amazon.com/images/I/712YSZbKx1L._AC_UL320_.jpg", fit: "A large multi-compartment kit bag listing for complete match-day gear." },
      { asin: "B07NYWV2LF", price: "₹1,335", title: "THRAX Super Pack Wheel Cricket Kit Bag", image: "https://m.media-amazon.com/images/I/61+x8EAbZaL._AC_UL320_.jpg", fit: "A wheeled kit-bag format for players carrying a fuller match setup." },
      { asin: "B0DWML95LH", price: "₹1,049", title: "Hundred Polyester Aspire Cricket Kitbag", image: "https://m.media-amazon.com/images/I/814EhwYp+vL._AC_UL320_.jpg", fit: "A spacious black-and-red bag with compartments for organised travel." },
      { asin: "B0DWMP4VCZ", price: "₹799", title: "Hundred Polyester Drive Cricket Kitbag", image: "https://m.media-amazon.com/images/I/71GzCMXcB2L._AC_UL320_.jpg", fit: "A navy multi-compartment option for bats, pads, gloves and accessories." },
      { asin: "B0B2NYW794", price: "₹1,190", title: "THRAX Power Pack Duffle Cricket Kit Bag", image: "https://m.media-amazon.com/images/I/51kOzea43uL._AC_UL320_.jpg", fit: "A duffle format for players who want a compact, easy-carry setup." },
      { asin: "B0G6GCSTW7", price: "₹602", title: "Lightweight Nylon Cricket Kit Backpack", image: "https://m.media-amazon.com/images/I/51oZhNYVMwL._AC_UL320_.jpg", fit: "A backpack-style option with side bat pockets for quick sessions." },
    ],
  },
  {
    id: "stumps-bails",
    label: "Stumps and bails",
    search: "cricket stumps",
    eyebrow: "Wickets · practice · match setup",
    title: "Stumps and wicket sets",
    description: "Portable wicket sets for grounds, schools, society cricket and home practice. Compare base style and set contents on Amazon.",
    accent: "gold",
    products: [
      { asin: "B0HKJ4JP4H", price: "₹3,880", title: "Virat Kohli Signature Series Cricket Kit for Kids", image: "https://m.media-amazon.com/images/I/71sqnG0-TuL._AC_UL320_.jpg", fit: "A youth cricket kit listing for players starting out with a complete set." },
      { asin: "B0FQJZ8GV1", price: "₹299", title: "Boldfit Cricket Stumps with Stand and Bails", image: "https://m.media-amazon.com/images/I/417104xA6JL._AC_UL320_.jpg", fit: "A plastic wicket set with stand and bails for portable practice." },
      { asin: "B0GPWM9PYP", price: "₹864.97", title: "Shrey Rubber Base Full Size Cricket Stumps", image: "https://m.media-amazon.com/images/I/61PZpffT-WL._AC_UL320_.jpg", fit: "A full-size three-wicket set for training grounds and society matches." },
      { asin: "B0GPWKTPGZ", price: "₹1,439.60", title: "Shrey Heritage Full Size Wooden Cricket Stump Set", image: "https://m.media-amazon.com/images/I/61pIiEm-z-L._AC_UL320_.jpg", fit: "A wooden six-stump and four-bail set for a more traditional setup." },
      { asin: "B0HHZCL143", price: "₹299", title: "Veer Sports Heavy Plastic Cricket Stumps Set", image: "https://m.media-amazon.com/images/I/41wmPX9oURL._AC_UL320_.jpg", fit: "A heavy plastic three-stump set with stand and bails for portable play." },
      { asin: "B0GL212QZM", price: "₹287", title: "Heavy Plastic Full Size Cricket Stumps", image: "https://m.media-amazon.com/images/I/61-kQN+-heL._AC_UL320_.jpg", fit: "A larger wicket set with stands for grounds and tournament practice." },
    ],
  },
  {
    id: "training-equipment",
    label: "Training equipment",
    search: "cricket training equipment",
    eyebrow: "Reflex · speed · skill work",
    title: "Training lab",
    description: "Rebound tools, agility kits, catching aids and practice equipment for batting, bowling, fielding and fitness work.",
    accent: "cyan",
    products: [
      { asin: "B0HKVYS2FX", price: "₹2,299", title: "Cricket Katchet Board Slip Catch Trainer", image: "https://m.media-amazon.com/images/I/81uBTAGYdPL._AC_UL320_.jpg", fit: "A reflex and rebound board listing for slip catching, fielding and keeping drills." },
      { asin: "B0HKW6DKF7", price: "₹990", title: "Speed and Agility Cricket Training Kit", image: "https://m.media-amazon.com/images/I/51KP70Q3jHL._AC_UL320_.jpg", fit: "A multi-piece ladder, cones, hurdles and parachute kit for movement work." },
      { asin: "B0H7B1DLNL", price: "₹799", title: "JAXTON Junction Agility Combo Cricket Kit", image: "https://m.media-amazon.com/images/I/61P4K+fb4RL._AC_UL320_.jpg", fit: "A cricket-friendly agility combo for speed, footwork and conditioning." },
      { asin: "B0H94S52MG", price: "₹299", title: "Lifelong Tennis Trainer Rebound Ball Set", image: "https://m.media-amazon.com/images/I/61a7Skv0pwL._AC_UL320_.jpg", fit: "A solo rebound-ball trainer for hand-eye coordination and repeated contact." },
      { asin: "B0HJMSY7LL", price: "₹199", title: "Hanging Cricket Tennis Practice Ball", image: "https://m.media-amazon.com/images/I/61ictRhSrRL._AC_UL320_.jpg", fit: "A hanging practice ball for timing, reflexes and compact-space batting drills." },
      { asin: "B0GHNSJ1F6", price: "₹1,299", title: "JAXTON Agility Kit for Cricket and Fitness", image: "https://m.media-amazon.com/images/I/513wAIXakLL._AC_UL320_.jpg", fit: "A general sports and fitness kit for warm-ups, footwork and conditioning." },
    ],
  },
];
